[project]
name = "stamp-stock-manager"
version = "0.1.0"
requires-python = "~=3.12.0"
dependencies = [
    "Django>=5.2,<5.3",
    "dj-database-url>=2.3,<3",
    "psycopg[binary]>=3.2,<4",
    "python-dotenv>=1.0,<2",
]

[tool.vercel]
entrypoint = "stamp_manager.wsgi:application"

[tool.vercel.scripts]
build = "python manage.py migrate --noinput"
