# Generated by Django 5.2.17 on 2026-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('product', 'Normal Product Sale'), ('wood_stamp', 'Wood Stamp')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('custom', 'Custom'), ('wood_stamp', 'Wood Stamp')], default='stock', max_length=20),
        ),
    ]
